In [1]:
import pandas as pd

import ast

In [2]:
legislators_current = pd.read_csv('/Users/kayliemendoza/Desktop/COGS108 Final Project/csv_output/legislators-current.csv')
legislators_historical = pd.read_csv('/Users/kayliemendoza/Desktop/COGS108 Final Project/csv_output/legislators-historical.csv')

legislators = pd.concat([legislators_current, legislators_historical], ignore_index=True)

In [ ]:
from legislators_maybe.extract_legislators_info import extract_legislators_info

# Apply the extract_legislators_info function
legislators_extracted = legislators.apply(lambda row: pd.Series(extract_legislators_info(row)), axis=1)

# Combine the extracted columns with the original DataFrame
legislators = pd.concat([legislators, legislators_extracted], axis=1)

In [4]:
from functions.get_zodiac_sign import get_zodiac_sign

# Apply the zodiac sign function to the 'birthday' column
legislators['zodiac_sign'] = legislators['birthday'].apply(get_zodiac_sign)

In [5]:
# Import the get_zodiac_color function
from functions.zodiac_color_mapping import get_zodiac_color

# Add a new column for zodiac colors in the executive DataFrame
legislators['zodiac_color'] = legislators['zodiac_sign'].apply(get_zodiac_color)

In [6]:
from test_calculate_term_ages import calculate_term_ages_vectorized

# Apply the vectorized function to calculate ages
ages = calculate_term_ages_vectorized(legislators)

# Combine the calculated ages with the original DataFrame
legislators = pd.concat([legislators, ages], axis=1)

In [7]:
##from functions.calculate_term_ages import calculate_term_ages

# Apply the function to calculate ages
##ages = legislators.apply(lambda row: pd.Series(calculate_term_ages(row)), axis=1)

# Combine the calculated ages with the original DataFrame
##legislators = pd.concat([legislators, ages], axis=1)

In [8]:
from functions.calculate_term_duration import calculate_term_duration

# Apply the function to calculate term durations
term_durations = legislators.apply(lambda row: pd.Series(calculate_term_duration(row)), axis=1)

# Combine the calculated durations with the original DataFrame
legislators = pd.concat([legislators, term_durations], axis=1)

In [9]:
from functions.create_full_name import create_full_name 

# Apply the function to create the 'full_name' column
legislators['full_name'] = legislators.apply(create_full_name, axis=1)

In [10]:
columns_to_keep = ['full_name', 'birthdate', 'birthday', 'gender', 'type', 'start_term', 'end_term', 'state', 'class', 'district', 'party', 'how', 
'zodiac_sign', 'age_start', 'age_end', 'duration_days', 'duration_years', 'duration_months']

# Create a new DataFrame with only the specified columns
filtered_legislators = legislators[columns_to_keep]

In [11]:
filtered_legislators

,full_name,birthdate,birthday,gender,type,start_term,end_term,state,class,district,party,how,zodiac_sign,age_start,age_start,age_end,age_end,duration_days,duration_years,duration_months
0,Maria Cantwell,1958-10-13,10-13,F,rep,1993-01-05,1995-01-03,WA,NaN,1.0,Democrat,None,Libra,34.0,34.0,36.0,36.0,728.0,1.0,12.0
1,Amy Jean Klobuchar,1960-05-25,05-25,F,sen,2007-01-04,2013-01-03,MN,1.0,NaN,Democrat,None,Gemini,46.0,46.0,52.0,52.0,2191.0,6.0,0.0
2,Bernard 'Bernie' Sanders,1941-09-08,09-08,M,rep,1991-01-03,1993-01-03,VT,NaN,0.0,Independent,None,Virgo,49.0,49.0,51.0,51.0,731.0,2.0,0.0
3,Sheldon Whitehouse,1955-10-20,10-20,M,sen,2007-01-04,2013-01-03,RI,1.0,NaN,Democrat,None,Libra,51.0,51.0,57.0,57.0,2191.0,6.0,0.0
4,John A. Barrasso,1952-07-21,07-21,M,sen,2007-06-25,2013-01-03,WY,1.0,NaN,Republican,appointment,Cancer,54.0,54.0,60.0,60.0,2019.0,5.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12754,James David 'J.D.' Vance,1984-08-02,08-02,M,sen,2023-01-03,2025-01-09,OH,3.0,NaN,Republican,None,Leo,38.0,38.0,40.0,40.0,737.0,2.0,0.0
12755,Marco Rubio,1971-05-28,05-28,M,sen,2011-01-05,2017-01-03,FL,3.0,NaN,Republican,None,Gemini,39.0,39.0,45.0,45.0,2190.0,6.0,0.0
12756,Michael Waltz,1974-01-31,01-31,M,rep,2019-01-03,2021-01-03,FL,NaN,6.0,Republican,None,Aquarius,44.0,44.0,46.0,46.0,731.0,2.0,0.0
12757,Sylvester Turner,1954-09-27,09-27,M,rep,2025-01-03,2025-03-04,TX,NaN,18.0,Democrat,None,Libra,70.0,70.0,70.0,70.0,60.0,0.0,2.0
12758,Raúl M. Grijalva,1948-02-19,02-19,M,rep,2003-01-07,2005-01-03,AZ,NaN,7.0,Democrat,None,Pisces,54.0,54.0,56.0,56.0,727.0,1.0,12.0

In [12]:
# Save the cleaned DataFrame
filtered_legislators.to_csv('cleaned_legislators.csv', index=False)

possible visualization of the 'special cases' ?

In [13]:
# Get unique values of the 'how' column
unique_how_values = filtered_legislators['how'].unique()
print("Unique values in the 'how' column:")
print(unique_how_values)

Unique values in the 'how' column:
[None 'appointment' 'special-election']